### ISSUE TITLE
Chapter 6: Trading Rule Identification - tensorflow_setup missing

### ISSUE THREAD

**Issue by WongYatChun** [PacktPublishing/Hands-On-Deep-Learning-for-Finance#1]
Chapter 6: tensorflow_setup missing

Assume we create the same tensorflow_setup.py following the book,  it will give error message: 'h5files/hdf_50.h5', errno = 2, error message = 'No such file or directory'

**Comment by abhandari73** [comment]
In the preceding step the results have been saved in the h5files directory. The plot function refers to that file for plotting.

**Comment by sgkcfc** [comment]
where is the tensorflow setup file in this repo.

**Comment by abhandari73** [comment]
added

**Comment by sgkcfc** [comment]
@WongYatChun you need to create a folder with name h5files to do away with that error
