### ISSUE TITLE
uncommented line in prediction_Accuracy

### ISSUE THREAD

**Issue by sgkcfc** [PacktPublishing/Hands-On-Deep-Learning-for-Finance#12]
there is an uncommented line in prediction_accurary that results in error when running the prediction_accuracy function

Also could you please provide an example in one of the tensorflow files for the heat map generation. I cant wrap my head around it since classification is on many epochs.

**Comment by abhandari73** [comment]
Please refer to Chap06- directory. The codes have been organized in ipynb files.
