### ISSUE TITLE
trading rule identification with cnn

### ISSUE THREAD

**Issue by sgkcfc** [PacktPublishing/Hands-On-Deep-Learning-for-Finance#2]
The book and the code are ways apart. Perhaps provide a readme to the updated code.  

some of the code is not compilable 
e.g **%matplotlib inline** is invalid syntax. 
no updated instructions as to how to create the sample data

**Comment by sgkcfc** [comment]
in addition to it code i seeking csv folder. all data is present in sample data folder. that code needs to be updated.

**Comment by abhandari73** [comment]
The cvv files are provided as a sample. You will need to use your own data. 
%matplotlib inline is used in jupyter notebooks to visualize the plots inline. It can be omitted if you have newer installation.

**Comment by sgkcfc** [comment]
i was thinking if it its a jupyter notebook it would be nice to have a ipynb extension to it. 
all the code in book refers to symbol list and then pulling the data. for the purpose of the book might as well move the sample data to the csv folder so that the code works?

**Comment by abhandari73** [comment]
%matplotlib inline can be used in IPython
