### ISSUE TITLE
DIffrence in results in trading rule identification with CNN

### ISSUE THREAD

**Issue by sgkcfc** [PacktPublishing/Hands-On-Deep-Learning-for-Finance#9]
Could you please upload the reference data that was used in the code.
This would help the readers to corelate the results with the ones in book, and play around with the data .

**Comment by sgkcfc** [comment]
example, i used apple data and results are very different with only 50% training and testing accuracy. IT would help to cross validate the data in such situations.

**Comment by abhandari73** [comment]
This book is about the techniques one can use to analyze data. Reference data is provided in csvfiles directory and h5files directory. You need to analyze the results for each of the techniques in the context of your own data. The tenet is that deep learning techniques offer an improvement over the basic ML methods.

**Comment by sgkcfc** [comment]
I agree  with your premise. Using any data csv data downloaded from yahoo qualifies for using Our own data. However i still didnt get what reference data was used since there was no end to end code that we didn't have to modify to make it work.
